# coding: utf-8

"""
    javazone-catalog-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from catalog_client.models.field_dto import FieldDTO

class TestFieldDTO(unittest.TestCase):
    """FieldDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldDTO:
        """Test FieldDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldDTO`
        """
        model = FieldDTO()
        if include_optional:
            return FieldDTO(
                name = '0',
                type = '0'
            )
        else:
            return FieldDTO(
                name = '0',
                type = '0',
        )
        """

    def testFieldDTO(self):
        """Test FieldDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
