# coding: utf-8

# flake8: noqa

"""
    javazone-catalog-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "DatasetsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "DatasetDTO",
    "DatasetSensitivity",
    "FieldDTO",
]

# import apis into sdk package
from catalog_client.api.datasets_api import DatasetsApi as DatasetsApi

# import ApiClient
from catalog_client.api_response import ApiResponse as ApiResponse
from catalog_client.api_client import ApiClient as ApiClient
from catalog_client.configuration import Configuration as Configuration
from catalog_client.exceptions import OpenApiException as OpenApiException
from catalog_client.exceptions import ApiTypeError as ApiTypeError
from catalog_client.exceptions import ApiValueError as ApiValueError
from catalog_client.exceptions import ApiKeyError as ApiKeyError
from catalog_client.exceptions import ApiAttributeError as ApiAttributeError
from catalog_client.exceptions import ApiException as ApiException

# import models into sdk package
from catalog_client.models.dataset_dto import DatasetDTO as DatasetDTO
from catalog_client.models.dataset_sensitivity import DatasetSensitivity as DatasetSensitivity
from catalog_client.models.field_dto import FieldDTO as FieldDTO

from catalog_client.auth import authenticated_client  # added by scripts/patch_python_client.py
